### ISSUE TITLE
if comma in script ,it will be separate two commands?

### ISSUE THREAD

**Issue by rinetd** [appleboy/drone-ssh#102]
sample:
```
    script:
       - sed -i "s|'hostname'       => .*|'hostname'       => 'mysql',|g" config.php
```
will be separate two error commands like this

`sed -i "s|'hostname'       => .*|'hostname'       => 'mysql'`
`|g" config.php`

**Comment by appleboy** [comment]
@rinetd Please open the new file and write your script so just run the script as the following:

```yaml
script:
  - sh build.sh
```

**Comment by b12f** [comment]
This solution does not work for me. I'm currently trying to deploy docker containers with this, and need to do a bit of bash scripting to add some ENV variables.

On the server itself, there are no files present of the actual project, and I don't want there to be any, otherwise I would have to clone the project onto the server just to get the build script. I'd like it to be: just ssh in, start the container, and exit.

The following script fails for me:
```
 - |
            export CONTAINER=lnb;
            export VIRTUAL_HOST='latenight.blue,eleventhirty.am';

            docker pull docker.b12f.io/b12f/latenight.blue:${DRONE_TAG};
            docker stop $CONTAINER || true;
            docker rm $CONTAINER || true;
            docker run -d --name $CONTAINER -e VIRTUAL_PORT=3000 -e VIRTUAL_HOST=$VIRTUAL_HOST -e LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL -e LETSENCRYPT_HOST=$VIRTUAL_HOST --restart always --network nginx-proxy docker.b12f.io/b12f/latenight.blue:${DRONE_TAG};
            docker system prune -f;
```
This outputs `lnb latenight.blue eleventhirty.am`, which breaks the docker run command, because I expect to be able to put the `VIRTUAL_HOST` env variable into a container. Instead, it only sets `latenight.blue`, and tries to start a non-existing `eleventhirty.am:latest` container.

**Comment by appleboy** [comment]
Please try v1.6.7 version.

**Comment by appleboy** [comment]
duplicated of #60
