### ISSUE TITLE
Have a setting for not autoloading .env data

### ISSUE THREAD

**Issue by albertyw** [appleboy/drone-ssh#239]

**Comment by Polectron** [comment]
Yes please, the last update broke my ci pipeline.
I'm using `appleboy/ssh-action` to deploy a django application which has a .env with `DEBUG=on`, this breaks drone-ssh because it doesn't have the expected format.
Honestly I think drone-ssh should never load a .env by default, it should be opt in to load it.

**Comment by albertyw** [comment]
I created two pull requests for this issue:

#242 adds the ability for a user to disable automatically loading `.env` files.  It is backwards compatible.
#243 disables automatically loading `.env` files.  It is not backwards compatible but it is simpler.

The two conflict with each other so only one can be merged.  I personally would prefer #243.
